class NotFoundPostError(Exception):
    pass


class NotFoundUserError(Exception):
    pass
